name: Local Windows Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Add your build and test steps here
    
    - name: Install PowerShell
      if: runner.os == 'Windows'
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install powershell -y
        
    - name: Get Public IP
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $publicIP = (Invoke-WebRequest -Uri 'https://api.ipify.org').Content
        Write-Output "Public IP Address: $publicIP"
