name: windows

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CRD Code'
        required: true
      pincode:
        description: '6 digit PIN'
        required: true
        
jobs:
  setup:
    runs-on: windows-latest
    steps:
    - name: Install Winget
  run: Invoke-WebRequest -Uri 'https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -OutFile 'winget.msixbundle'
    msiexec /i winget.msixbundle /quiet /qn /norestart

    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: NirCMD Setup
      run: ./prog.bat
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
