name: SSH to External IP

on: [push]

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to Server and Execute Command
      run: |
        ssh -o StrictHostKeyChecking=no slayer@192.168.230.134 "ls -l /home/slayer"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
